--- 
abstract: making pluggable applications easy
author: Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>
build_requires: 
  Test::More: 0
  UNIVERSAL::require: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Hook-Modular
no_index: 
  directory: 
    - inc
    - t
requires: 
  Cache::FileCache: 0
  Class::Accessor::Fast: 0
  Encode: 0
  File::Find::Rule: 0
  File::HomeDir: 0
  List::Util: 0
  MIME::Base64: 0
  Module::Pluggable::Fast: 0
  Scalar::Util: 0
  UNIVERSAL::require: 0
  YAML: 0
version: 0.05
