---
abstract: 'Making pluggable applications easy'
author:
  - 'Tatsuhiko Miyagawa C<< <miyagawa@bulknews.net> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hook-Modular
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Cache::FileCache: 0
  Class::Accessor::Fast: 0
  Encode: 0
  File::Find::Rule: 0
  File::HomeDir: 0
  List::Util: 0
  MIME::Base64: 0
  Module::Pluggable::Fast: 0
  Scalar::Util: 0
  UNIVERSAL::require: 0
  YAML: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Hook-Modular
  homepage: http://search.cpan.org/dist/Hook-Modular/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/hook-modular.git
version: 0.08
